### PR TITLE
fix: toHaveSelector when ElementHandle is passed

### LINKED ISSUE #117: 0.7.0 has broken expecting on ElementHandle
v0.6.0 works fine.

Updating to 0.7.1 fails tests.

Trying to
```js
const firstWidgetOfUser = await page.waitForSelector(DashboardSelectors.widget);
// works
expect(await firstWidgetOfUser.getAttribute('data-id')).toStrictEqual('File/my_open_cases');
// fails in 0.7.0/0.7.1, works fine in 0.6.0
await expect(firstWidgetOfUser).toHaveSelector(DashboardSelectors.chartWidget);
```
fails on second `expect` with

`TypeError: Cannot read property 'waitForSelector' of null`;

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes #117

### CODE REVIEW

File: src/matchers/utils.ts [hunk 1]
```diff
@@ -10,7 +10,7 @@ const isElementHandle = (value: Handle): value is ElementHandle => {
 
 export const getFrame = async (value: ExpectInputType) => {
   const resolved = await value
-  return isElementHandle(resolved) ? resolved.contentFrame() : resolved
+  return isElementHandle(resolved) ? await resolved.contentFrame() : resolved
```
Comment (mskelton) [inline src/matchers/utils.ts:13]: Since this method is async, awaiting isn't needed since it will return a promise that must be awaited anyway.

```suggestion
  return isElementHandle(resolved) ? resolved.contentFrame() : resolved
```

File: src/matchers/toHaveSelectorCount/index.ts [hunk 2]
```diff
@@ -9,10 +9,13 @@ const toHaveSelectorCount: jest.CustomMatcher = async function (
   options: PageWaitForSelectorOptions = {}
 ): Promise<SyncExpectationResult> {
   try {
-    const frame = (await getFrame(arg))!
-    await frame.waitForSelector(selector, { state: "attached", ...options })
+    const [elementHandle] = await getElementHandle([arg, selector], 1)
```
Comment (mskelton) [inline src/matchers/toHaveSelectorCount/index.ts:12]: Shouldn't we pass options to `getElementHandle`?

File: src/matchers/toHaveSelector/index.test.ts [hunk 3]
```diff
@@ -8,6 +8,12 @@ describe("toHaveSelector", () => {
     await page.setContent(`<div id="foobar">Bar</div>`)
     await expect(page).toHaveSelector("#foobar")
   })
+  it("positive with an element handle", async () => {
+    await page.setContent(`<div id="foobar">Bar</div>`)
+    const handle = await page.$("#foobar")
+    expect(handle).toBeTruthy()
+    await expect(handle).toHaveSelector("#foobar")
```
Comment (mskelton) [inline src/matchers/toHaveSelector/index.test.ts:15]:
```suggestion
    await page.setContent(`<div id="foo"><div id="bar">Baz</div></div>`)
    const handle = await page.$("#foo")
    expect(handle).toBeTruthy()
    await expect(handle).toHaveSelector("#bar")
```

**Review by mskelton — APPROVED** [review]
